//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCA__Gerenciador_de_Chaves_de_Ativação_
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Idiomas
    {
        public int ID_Idioma { get; set; }
        public string Idioma { get; set; }
        public string País { get; set; }
        public string Sigla { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
