//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCA__Gerenciador_de_Chaves_de_Ativação_
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Software
    {
        public int ID_Software { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public Nullable<int> ID_Maquina { get; set; }
        public Nullable<int> ID_Setor { get; set; }
        public string NomeDoSoftware { get; set; }
        public string TipoDeSoftware { get; set; }
        public string PrazoLicenca { get; set; }
        public string Idioma { get; set; }
        public string Sistema { get; set; }
        public string Fabricante { get; set; }
        public string Versao { get; set; }
        public string ChaveDeAtivacao { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
