//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCA__Gerenciador_de_Chaves_de_Ativação_
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuario
    {
        public int ID_Usuario { get; set; }
        public string NomeUsuario { get; set; }
        public string Funcao { get; set; }
        public string Setor { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
